### ISSUE TITLE
TypeScript checks in the project fails after upgrading to 1.0.1

### ISSUE THREAD

**Issue by rakeshpetit** [expo/router#312]
### Summary

Running `yarn tsc` for checking TypeScript errors fails on stable release `1.0.1`. I have now reverted back to `1.0.0-rc3` which works fine.

### Minimal reproducible example

```
yarn tsc
yarn run v1.22.18
$ tsc
node_modules/expo-router/src/ExpoRoot.tsx:19:64 - error TS2307: Cannot find module 'react-native-gesture-handler' or its corresponding type declarations.

19       require("react-native-gesture-handler") as typeof import("react-native-gesture-handler");
                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/expo-router/src/ExpoRoot.tsx:19

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
